#!/bin/sh
# Setup a machine for VSCode
set -x

vscode_dir=~/Library/Application\ Support/Code
ln -s "$PWD/User" "$vscode_dir/User"

code --install-extension adpyke.codesnap
code --install-extension Atishay-Jain.All-Autocomplete
code --install-extension christian-kohler.npm-intellisense
code --install-extension cnakazawa.dunkel-theme
code --install-extension cnakazawa.licht-theme
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-rename-tag
code --install-extension GitHub.copilot
code --install-extension GitHub.copilot-chat
code --install-extension github.vscode-github-actions
code --install-extension GraphQL.vscode-graphql
code --install-extension GraphQL.vscode-graphql-syntax
code --install-extension johnsoncodehk.vscode-code-spotlight
code --install-extension MarkosTh09.color-picker
code --install-extension mikestead.dotenv
code --install-extension mrmlnc.vscode-duplicate
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode.live-server
code --install-extension nhoizey.gremlins
code --install-extension tamasfe.even-better-toml
code --install-extension unifiedjs.vscode-mdx
code --install-extension usernamehw.errorlens
code --install-extension wix.vscode-import-cost
code --install-extension ziyasal.vscode-open-in-github


code --install-extension aaron-bond.better-comments
code --install-extension adamhartford.vscode-base64
code --install-extension adpyke.codesnap
code --install-extension Atishay-Jain.All-Autocomplete
code --install-extension CircleCI.circleci
code --install-extension darkriszty.markdown-table-prettify
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension Gruntfuggly.todo-tree
code --install-extension hashicorp.terraform
code --install-extension jakebathman.mysql-syntax
code --install-extension jianbingfang.dupchecker
code --install-extension mrmlnc.vscode-duplicate
code --install-extension ms-mssql.data-workspace-vscode
code --install-extension ms-mssql.mssql
code --install-extension ms-mssql.sql-bindings-vscode
code --install-extension ms-mssql.sql-database-projects-vscode
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.remote-server
code --install-extension redhat.vscode-commons
code --install-extension redhat.vscode-yaml
code --install-extension timonwong.shellcheck
code --install-extension tsandall.opa
code --install-extension usernamehw.errorlens
code --install-extension waderyan.gitblame
code --install-extension wayou.vscode-todo-highlight
code --install-extension yzhang.markdown-all-in-one